export const ROUTES = {
  RECIPIENTS: '/recipients',
  BUSINESS: '/business',
  PAYERS: '/payers',
  AGENTS: '/agents',
  SUPPORT: '/support',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  ABOUT_US: '/about-us',
  CREDENTIALS: '/credentials',
  PRIVACY_POLICY: '/privacy-policy',
  PUBLIC_OFFER: '/public-offer',
  FAQ: '/faq',
  MY_QR_CODES: '/qr-codes',
  MY_REQUISITES: '/requisites',
  MY_PLATFORMS: '/platforms',
  MY_EMPLOYEES: '/employees',
  MY_REVIEWS: '/reviews',
  PERSONAL_DATA: '/personal',
  QR_CREATE: '/qr/create',
  THANK_YOU: '/thank-you',
  FOR_AGENTS: '/for-agents',
  LOYALTY: '/loyalty'
}
