export const ROUTES = {
  RECIPIENTS: '/recipients',
  BUSINESS: '/business',
  PAYERS: '/payers',
  AGENTS: '/agents',
  SUPPORT: '/support',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  ABOUT_US: '/about-us',
  CREDENTIALS: '/credentials',
  PRIVACY_POLICY: '/privacy-policy',
  PUBLIC_OFFER: '/public-offer',
  FAQ: '/faq',
  ACCOUNT_MY_QR_CODES: '/account/qr-codes',
  ACCOUNT_MY_REQUISITES: '/account/requisites',
  ACCOUNT_MY_PLATFORMS: '/account/platforms',
  ACCOUNT_MY_EMPLOYEES: '/account/employees',
  ACCOUNT_MY_REVIEWS: '/account/reviews',
  ACCOUNT_PERSONAL_DATA: '/account/personal',
  ACCOUNT_QR_CREATE: '/account/qr/create',
  THANK_YOU: '/thank-you',
  FOR_AGENTS: '/for-agents',
  LOYALTY: '/loyalty'
}
